name: CI Pipeline

on:
  push:
    branches: [ "main", "desenvolvimento" ]
  pull_request:
    branches: [ "main", "desenvolvimento" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Testar build da imagem Docker
      run: |
        docker build -t codefactory-app .